apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 2 # Menjalankan 2 replika web app agar high availability
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        # Image ini akan otomatis terupdate oleh Github Actions ketika Anda push
        image: gerardomayella/web-app-for-kube:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
      # Hapus tanda '#' di bawah ini jika Anda ingin mengunci agar web app ini HANYA berjalan di worker-1
      # nodeSelector:
      #   peruntukan: web-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 1 # Database cukup 1 replika agar datanya konsisten
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rahasia123"
        - name: MYSQL_DATABASE
          value: "mydb"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
      # Hapus tanda '#' di bawah ini jika Anda ingin mengunci agar database ini HANYA berjalan di worker-2
      # nodeSelector:
      #   peruntukan: database
